[package]
name = "dpino"
version = "0.1.0"
edition = "2021"
authors = ["Abdou <aabdou911aydev@gmail.com>"]
description = "A Rust-powered package metadata extractor + desktop entry generator + installer + browser"
license = "MIT OR Apache-2.0"
repository = "https://github.com/abdou-da0wew/dpino"

[dependencies]
clap = { version = "^4", features = ["derive"] }
walkdir = "^2"
ar = "^0.9"
tar = "^0.4"
xz2 = "^0.1"
flate2 = "^1"
ratatui = "^0.26"
crossterm = "^0.27"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
thiserror = "^1"
anyhow = "^1"
tempfile = "^3"
log = "^0.4"
env_logger = "^0.10"

[dev-dependencies]
assert_fs = "^1"

[lib]
name = "dpino"
path = "src/lib.rs"

[[bin]]
name = "dpino"
path = "src/main.rs"
