name: Publish AUR
on:
  push:
    tags: ['v*']
jobs:
  aur:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update AUR package
      uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
      with:
        pkgname: dpino
        pkgbuild: packaging/aur/PKGBUILD
        updpkgsums: true
        commit_username: "Release Bot"
        commit_email: "bot@example.com"
        ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
